server:
  port: 8761

# 本服务名称
spring:
  application:
    name: shopping-zuul

# 服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

# 路由配置
#zuul:
#  routes:
#    demo-feign-freeservice:
#      path: /api-service/**

